name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  AWS_REGION: eu-north-1  
  ECR_REGISTRY: 637423323200.dkr.ecr.eu-north-1.amazonaws.com
  ECR_REPOSITORY: webapp

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Client
        working-directory: ./ui
        run: |
          npm install
          npm run build

      - name: Install Server
        working-directory: ./api
        run: |
          npm install
          npm run build

      - name: Install AWS Tools for PowerShell
        shell: pwsh
        run: |
          Install-Module -Name AWSPowerShell -Force -Scope CurrentUser

      - name: Authenticate to Amazon ECR
        shell: pwsh
        run: |
          (Get-ECRLoginCommand -Region ${{ env.AWS_REGION }}).Password | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.ECR_REPOSITORY }} .

      - name: Tag Docker Image
        run: |
          docker tag ${{ env.ECR_REPOSITORY }}:latest ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest

      - name: Push Docker Image to Amazon ECR
        run: |
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
